# Generated by Django 3.2.9 on 2021-11-28 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
